package AdminInterfaces;

import MainInterfaces.DBAccess;
import Mundo.EventCategory;
import Mundo.EventType;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;

public class Edit_EventType extends javax.swing.JFrame {

    boolean edit;
    
    public Edit_EventType(boolean edit) {
        this.edit = edit;
        initComponents();
        setVisible(true);
        if(edit){
            editar();
        }else{
            nuevo();
        }
    }

    public void editar(){
        ArrayList parametros = new ArrayList();
        parametros.add(EventType.getETYPE_ID());
        for(int i = 0; i < 3; i++) parametros.add(Types.VARCHAR);
        try {
            ArrayList<String> datosUsuario = DBAccess.procedureIN_OUT("ETYPE_INFORMATION(?,?,?,?)", parametros);
            selCategories.setModel(new DefaultComboBoxModel(DBAccess.llenarCB(datosUsuario.get(0), DBAccess.rsToArray(DBAccess.consultar(EventCategory.getAllCategories())))));
            selName.setModel(new DefaultComboBoxModel(DBAccess.llenarCB(datosUsuario.get(1), DBAccess.rsToArray(DBAccess.consultar(EventType.getAllNames())))));
            textRestrictions.setText(datosUsuario.get(2));
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"ERROR: Al cargar la informacion de evento");
        }
    }
    
    public void nuevo(){
        try {
            selCategories.setModel(new DefaultComboBoxModel(DBAccess.rsToArray(DBAccess.consultar(EventCategory.getAllCategories()))));
            selName.setModel(new DefaultComboBoxModel(DBAccess.rsToArray(DBAccess.consultar(EventType.getAllNames()))));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"ERROR: Al cargar los tipos y/o categorias del evento");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textRestrictions = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        selCategories = new javax.swing.JComboBox<>();
        buttonEdit = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        selName = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tipo de Evento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Restricciones");

        textRestrictions.setColumns(20);
        textRestrictions.setRows(5);
        jScrollPane1.setViewportView(textRestrictions);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Categoría");

        buttonEdit.setText("Aceptar");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonExit.setText("Cancelar");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        selName.setEditable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonExit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(selCategories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonEdit))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        dispose();
        new Search_EventType();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        ArrayList parametros = new ArrayList();
        if(edit){
            parametros.add(EventType.getETYPE_ID());
            parametros.add((String)selCategories.getSelectedItem());
            parametros.add((String)selName.getSelectedItem());
            parametros.add(textRestrictions.getText());
            try {
                DBAccess.procedureIN("CHANGE_ETYPE_INFO(?,?,?,?)",parametros);
                JOptionPane.showMessageDialog(null,"Se hiso las modificaciones Exitosamente");
                dispose();
                new Search_EventType();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"No se pudo modificar el tipo de evento, los datos solicitados ya esta en uso o algun dato es erroneo");
                try {
                    DBAccess.getConexion().rollback();
                } catch (SQLException ex1) {
                    System.out.println("Error: Cargar la Base de Datos desde las ediciones de los tipos de eventos");
                }
            }  
        }else{
            parametros.add((String)selCategories.getSelectedItem());
            parametros.add((String)selName.getSelectedItem());
            parametros.add(textRestrictions.getText());
            try {
                DBAccess.procedureIN("CREATE_ETYPE(?,?,?)",parametros);
                JOptionPane.showMessageDialog(null,"Se creo el tipo de evento Exitosamente");
                dispose();
                new Search_EventType();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"No se pudo crear el tipo de evento, los datos solicitados ya esta en uso o algun dato es erroneo");
                try {
                    DBAccess.getConexion().rollback();
                } catch (SQLException ex1) {
                    System.out.println("Error: Cargar la Base de Datos desde la creacion de los tipos de evento");
                }
            }
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selCategories;
    private javax.swing.JComboBox<String> selName;
    private javax.swing.JTextArea textRestrictions;
    // End of variables declaration//GEN-END:variables
}
