package AdminInterfaces;

import MainInterfaces.DBAccess;
import Mundo.Admin.EventCategory;
import Mundo.Admin.EventType;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;

public class Edit_EventType extends javax.swing.JFrame {
    DBAccess dba;

    
    public Edit_EventType(DBAccess dba) {
        this.dba = dba;
        
        initComponents();
        
        try {
            EventCategory EventCategory = new EventCategory();
            ResultSet rsEventCategory = dba.consultar(EventCategory.getCategories());
            String[] arrayEventCategory = rsToArray(rsEventCategory);
            selCategories = new JComboBox(arrayEventCategory);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Mensaje de Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public String[] rsToArray(ResultSet data){
        ArrayList<String> items = new ArrayList<>(100);    
        try {
        while(data.next()){ items.add(data.getString(1)); }
        } catch(SQLException e){}
        return items.toArray(new String[items.size()]);
    }
    
    public String getDataFromRS(ResultSet data) {
        try{
            if(data.next()){ return data.getString(1); }
        } catch(SQLException e) {}
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textRestrictions = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        selCategories = new javax.swing.JComboBox<>();
        buttonEdit = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        selName = new javax.swing.JComboBox<>();
        buttonNewEvent = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tipo de Evento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Restricciones");

        textRestrictions.setColumns(20);
        textRestrictions.setRows(5);
        textRestrictions.setText("Solo mayores de edad");
        jScrollPane1.setViewportView(textRestrictions);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Categoría");

        selCategories.setEditable(true);
        selCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concierto", "Conferencia" }));
        selCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selCategoriesActionPerformed(evt);
            }
        });

        buttonEdit.setText("Aceptar");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonExit.setText("Cancelar");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonRemove.setText("Eliminar");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        selName.setEditable(true);
        selName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rock al Parque" }));
        selName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selNameActionPerformed(evt);
            }
        });

        buttonNewEvent.setText("Programar Evento");
        buttonNewEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selCategories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonExit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonEdit)
                                .addGap(10, 10, 10)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonNewEvent)
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(buttonNewEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonNewEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewEventActionPerformed
        new New_Event(dba);
    }//GEN-LAST:event_buttonNewEventActionPerformed

    private void selCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selCategoriesActionPerformed
        String ECATEGORY_ID = (String)selCategories.getSelectedItem();
        
        try {
            EventCategory EventCategory = new EventCategory();
            ECATEGORY_ID = EventCategory.getID(ECATEGORY_ID);
            ResultSet RSEventCategory = dba.consultar(ECATEGORY_ID);
            ECATEGORY_ID = getDataFromRS(RSEventCategory);

            EventType EventType = new EventType();
            ResultSet rsEventType = dba.consultar(EventType.getEvents(ECATEGORY_ID));
            String[] arrayEventType = rsToArray(rsEventType);
            selName = new JComboBox(arrayEventType);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Mensaje de Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_selCategoriesActionPerformed

    private void selNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selNameActionPerformed
        String RESTRICTIONS = (String)selName.getSelectedItem();
        
        try {
            EventType EventType = new EventType();
            RESTRICTIONS = EventType.getRestrictions(RESTRICTIONS);
            ResultSet RSEventType = dba.consultar(RESTRICTIONS);
            RESTRICTIONS = getDataFromRS(RSEventType);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Mensaje de Error",JOptionPane.ERROR_MESSAGE);
        }
        
        textRestrictions.setText(RESTRICTIONS);
    }//GEN-LAST:event_selNameActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        String ETYPE_ID = (String)selName.getSelectedItem();
        try {
            EventType EventType = new EventType();
            ETYPE_ID = EventType.getID(ETYPE_ID);
            ResultSet RSEventType = dba.consultar(ETYPE_ID);
            ETYPE_ID = getDataFromRS(RSEventType);

            Boolean make = dba.ejecutar(EventType.remove(ETYPE_ID));
            if (make == true) { System.out.println("Operation make it!"); } else { System.out.println("Operation with errors"); }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Mensaje de Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        String ETYPE_ID = (String)selName.getSelectedItem();
        String RESTRICTIONS = textRestrictions.getSelectedText();
        
        try {
            EventType EventType = new EventType();
            ETYPE_ID = EventType.getID(ETYPE_ID);
            ResultSet RSEventType = dba.consultar(ETYPE_ID);
            ETYPE_ID = getDataFromRS(RSEventType);

            Boolean make = dba.ejecutar(EventType.update(ETYPE_ID, RESTRICTIONS));
            if (make == true) { System.out.println("Operation make it!"); } else { System.out.println("Operation with errors"); }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Mensaje de Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonNewEvent;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> selCategories;
    private javax.swing.JComboBox<String> selName;
    private javax.swing.JTextArea textRestrictions;
    // End of variables declaration//GEN-END:variables
}
